// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

// option java_multiple_files = true;
// option java_package = "io.grpc.examples.routeguide";
// option java_outer_classname = "RouteGuideProto";
// option objc_class_prefix = "RTG";

// package routeguide;

// Interface exported by the server.
service CommaConnect {
  // A simple RPC.
  //
  // Obtains the suggested speed and SPaT at a given position.
  //
  // An approach with an empty name is returned if there's no intersection data at the given
  // position.
  rpc GetApproach(Vehicle) returns (Suggestion) {}
}

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
message Vehicle {
  double latitude = 1;
  double longitude = 2;
  double bearing = 3;
  string street = 4;
  double speed = 5;
}

// An approach defines relevant data at a given point.
//
// If an approach does not have a corresponding intersection, the name is empty.
message Suggestion {
  // The name of the corresponding intersection
  string intersection_name = 1;

  // The name of the corresponding phase
  int32 phase = 2;

  // The given Vehicle info
  Vehicle request = 3;

  // The suggested speed at the given point, calculated from Pengyuan's alogirthm
  int32 suggested_speed = 4;

  // The upcoming signal state, from BlueCity
  int32 signal_status = 5;

  // The time to signal change, in seconds, from BlueCity
  double time_to_change = 6;

}