# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comma_connect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63omma_connect.proto\"=\n\x07Vehicle\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x05\"\x99\x01\n\nSuggestion\x12\x19\n\x11intersection_name\x18\x01 \x01(\t\x12\r\n\x05phase\x18\x02 \x01(\t\x12\x19\n\x07request\x18\x03 \x01(\x0b\x32\x08.Vehicle\x12\x17\n\x0fsuggested_speed\x18\x04 \x01(\x05\x12\x15\n\rsignal_status\x18\x05 \x01(\x05\x12\x16\n\x0etime_to_change\x18\x06 \x01(\x05\x32\x36\n\x0c\x43ommaConnect\x12&\n\x0bGetApproach\x12\x08.Vehicle\x1a\x0b.Suggestion\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comma_connect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLE._serialized_start=23
  _VEHICLE._serialized_end=84
  _SUGGESTION._serialized_start=87
  _SUGGESTION._serialized_end=240
  _COMMACONNECT._serialized_start=242
  _COMMACONNECT._serialized_end=296
# @@protoc_insertion_point(module_scope)
