# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from openpilot.selfdrive.controls.lib.protobuf import comma_connect_pb2 as comma__connect__pb2


class CommaConnectStub(object):
    """option java_multiple_files = true;
    option java_package = "io.grpc.examples.routeguide";
    option java_outer_classname = "RouteGuideProto";
    option objc_class_prefix = "RTG";

    package routeguide;

    Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetApproach = channel.unary_unary(
                '/CommaConnect/GetApproach',
                request_serializer=comma__connect__pb2.Vehicle.SerializeToString,
                response_deserializer=comma__connect__pb2.Suggestion.FromString,
                )


class CommaConnectServicer(object):
    """option java_multiple_files = true;
    option java_package = "io.grpc.examples.routeguide";
    option java_outer_classname = "RouteGuideProto";
    option objc_class_prefix = "RTG";

    package routeguide;

    Interface exported by the server.
    """

    def GetApproach(self, request, context):
        """A simple RPC.

        Obtains the suggested speed and SPaT at a given position.

        An approach with an empty name is returned if there's no intersection data at the given
        position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommaConnectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetApproach': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApproach,
                    request_deserializer=comma__connect__pb2.Vehicle.FromString,
                    response_serializer=comma__connect__pb2.Suggestion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommaConnect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommaConnect(object):
    """option java_multiple_files = true;
    option java_package = "io.grpc.examples.routeguide";
    option java_outer_classname = "RouteGuideProto";
    option objc_class_prefix = "RTG";

    package routeguide;

    Interface exported by the server.
    """

    @staticmethod
    def GetApproach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommaConnect/GetApproach',
            comma__connect__pb2.Vehicle.SerializeToString,
            comma__connect__pb2.Suggestion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
